### ISSUE TITLE
Cannot use Base16 Themes

### ISSUE THREAD

**Issue by danielmaartens** [tajmone/highlight#3]
Hi @tajmone,

when I use the --base16 option - as indicated in the following line - to select the ashes base16 theme I get the following error:

`highlight -O rtf --base16 ashes file.js | pbcopy`

**`cannot open themes/base16/edit-kwrite.theme: No such file or directory`**

Please can you assist as to what is causing this issue ?

I am running a 2015 Macbook Pro with OSX Mojave...

**Comment by tajmone** [comment]
Ciao,

The reason it's not working is because you still have the use the `-s` option to provide the style name:

    -s, --style=<style>

Try using:

    highlight -O rtf --base16 -s ashes file.js | pbcopy

Basically, the `--base16` option is only telling Highlight to look for the specified theme inside the `themes/base16/` subfolder, instead of the main `themes/` folder; but you still need `-s` to specify the theme name (they are separate options).

**Comment by tajmone** [comment]
Also, if you look at the error message:

    cannot open themes/base16/edit-kwrite.theme: No such file or directory

You can see that Highlight is trying to find the `edit-kwrite` theme (which is the default if none is specified) inside the `themes/base16/` folder — i.e. you can see that it didn't recognize `ashes` as a theme name.

Anyhow, this is a bug, for Highlight shouldn't be looking for the default theme in the base16 folder. I'll open an issue on the upstream repository, so that André can fix it.

Thanks for letting us know.

**Comment by tajmone** [comment]
Issue opened on GitLab upstream repository for this bug where Highlight looks for the fallback theme in the wrong folder:

* https://gitlab.com/saalen/highlight/issues/113
